# Generated by Django 4.2.7 on 2025-10-15 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studysession',
            old_name='creator',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='studysession',
            old_name='is_online',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='meeting_link',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='subject',
        ),
        migrations.AddField(
            model_name='sessionparticipant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='duration_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='studysession',
            name='subject_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sessionparticipant',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='study_sessions.studysession'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='max_participants',
            field=models.IntegerField(default=4),
        ),
    ]
